# Generated by Django 6.0.2 on 2026-03-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customerprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerprofile",
            old_name="phone_numner",
            new_name="phone_number",
        ),
    ]
