# Generated by Django 6.0.2 on 2026-02-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_app", "0003_alter_fooditem_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooditem",
            old_name="vendor",
            new_name="restaurant",
        ),
    ]
